// defines the bits used for addressing
#define VIRTUAL_ADDRESS_NBITS 24
// bits used for physical memory
#define PHYSICAL_ADDRESS_NBITS 20
// bits used for a single page(frame)
#define FRAME_PAGE_NBITS 12 // 4 KB pages
// other constants
#define VIRTUAL_MEMORY_SIZE (1 << VIRTUAL_ADDRESS_NBITS)
#define PHYSICAL_MEMORY_SIZE (1 << PHYSICAL_ADDRESS_NBITS)
#define PAGE_FRAME_SIZE (1 << (VIRTUAL_ADDRESS_NBITS - FRAME_PAGE_NBITS))
#define PAGES_NUM (VIRTUAL_MEMORY_SIZE / (1 << FRAME_PAGE_NBITS))
#define PHY_FRAMES_NUM (PHYSICAL_MEMORY_SIZE / (1 << FRAME_PAGE_NBITS))
#define PAGE_TABLE_SIZE (PAGES_NUM * (FRAME_PAGE_NBITS + FRAME_FLAGS_NBITS))

#define PAGE_FLAGS_NBITS 4
#define FRAME_FLAGS_NBITS 4